name: wust_life
description: "武汉科技大学生活app"


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: 3.0.10
  flutter_svg: ^0.19.1
  floor: ^0.14.0
  html: ^0.14.0+4
  crypto: ^2.1.5

  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.14.0
  build_runner: ^1.7.3
  mockito: ^4.1.3
  http: ^0.12.2
  mobx_codegen: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/keys/

