name: wust_life
description: "武汉科技大学生活app"


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: 3.0.10
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  flutter_svg: any
  floor: ^0.14.0
  html: ^0.14.0+4
  crypto: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.14.0
  build_runner: ^1.7.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/idcard.svg
    - assets/icons/password.svg
    - assets/images/setu.png
    - assets/images/l2.png

