name: wuster
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: 3.0.10
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  flutter_svg: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/idcard.svg
    - assets/icons/password.svg
    - assets/images/setu.png

